### ISSUE TITLE
Version of Tensorflow/OpenCV

### ISSUE THREAD

**Issue by kevinmgagnon** [bobetocalo/bobetocalo_prl19#2]
Hi, I was wondering what version of Tensorflow, Bazel, and OpenCV you used for this project as I'm having some issues with compiling your code.

**Comment by bobetocalo** [comment]
Hi Kevin, you must compile tensorflow using the following sentence:
bazel build -j $(nproc) --config=monolithic //tensorflow:libtensorflow_cc.so

Bazel 0.13.0
Tensorflow 1.8.0
OpenCV 3.3.1

Best regards,
Roberto Valle

**Comment by emilianavt** [comment]
Thank you for the advice on how to build the prerequisite version of tensorflow. I have installed Bazel 0.13.0 and used the provided command to build Tensorflow 1.8.0. I have placed the tensorflow folder inside the `faces_framework/alignment/bobetocalo_prl19` folder. When attempting to compile `bobetocalo_prl19`, it fails at `FaceAlignmentPrl19.cpp.o` with numerous errors about an incompatible Protocol Buffers header version and finally this error:

    faces_framework/alignment/bobetocalo_prl19/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
     #include "unsupported/Eigen/CXX11/Tensor"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

Do you have any further advice on how to get it working?

**Comment by bobetocalo** [comment]
Hi Emilia,

This error seems like you do not have installed libeigen3-dev ...
According to the protobuf error. I encourage you to install protobuff manually instead of using the default packages. You can follow the instructions in https://github.com/google/protobuf.git
In my case, it works with the following version:
Protobuf 3.5.2

Best regards,
Roberto Valle

**Comment by emilianavt** [comment]
> This error seems like you do not have installed libeigen3-dev ...

I do have it installed. Actually, going by the error, the Tensor header included in the tensorflow source tree seems to include itself, which then fails. Looking around some more, I was able to find [this](https://stackoverflow.com/a/51074852) post which might contain a solution.

I will try installing Protobuf 3.5.2 from source, thank you.
